using System;
using System.Collections.Generic;
using Ustas.RimAI.Communication.Client.OpenAI;
namespace Ustas.RimAI.Communication.Data { public enum Role { System, User, AI } }
internal static class Program
{
 static int n; static void T(bool x,string s){if(!x)throw new Exception("FAILED "+s);n++;}
 public static int Main(){const string secret="fixture-secret"; string old=Environment.GetEnvironmentVariable(OpenAIProviderAdapter.CredentialVariable); string talk=Environment.GetEnvironmentVariable("OPENAI_RIMTALK"); string chat=Environment.GetEnvironmentVariable("OPENAI_RIMCHAT"); string trans=Environment.GetEnvironmentVariable("OPENAI_RIMTRANS"); string api=Environment.GetEnvironmentVariable("OPENAI_API_KEY"); try{
 var m=new List<(Ustas.RimAI.Communication.Data.Role role,string message)>{(Ustas.RimAI.Communication.Data.Role.System,"Українською"),(Ustas.RimAI.Communication.Data.Role.User,"Привіт")}; string q=OpenAIProviderAdapter.BuildRequest("gpt-5.6-luna",m,16);
 T(q.Contains("gpt-5.6-luna"),"01");T(q.Contains("Привіт"),"02");T(OpenAIProviderAdapter.ResponsesEndpoint.EndsWith("/v1/responses"),"03");T(q.Contains("max_output_tokens\":16"),"04");T(!q.Contains("max_tokens"),"05");T(!q.Contains("temperature"),"06");T(q.Contains("input_text"),"07");T(!q.Contains("Authorization"),"08");T(!q.Contains(secret),"09");T(q.Contains("developer"),"10");T(q.Contains("store\":false"),"11");T(!q.Contains("messages"),"12");
 var models=OpenAIProviderAdapter.ParseModels("{\"data\":[{\"id\":\"a\"},{\"id\":\"b\"}]}");T(models.Count==2,"13");T(OpenAIProviderAdapter.Classify(401,"")==OpenAIErrorCategory.Authentication,"14");T(OpenAIProviderAdapter.Classify(403,"")==OpenAIErrorCategory.Permission,"15");T(OpenAIProviderAdapter.Classify(429,"")==OpenAIErrorCategory.RateLimit,"16");T(OpenAIProviderAdapter.Classify(500,"")==OpenAIErrorCategory.Server,"17");bool bad=false;try{OpenAIProviderAdapter.ParseModels("{}");}catch(FormatException){bad=true;}T(bad,"18");T(models.Contains("a"),"19");T(!models.Contains("z"),"20");T(q.Contains("gpt-5.6-luna"),"21");T(OpenAIProviderAdapter.Classify(400,"invalid")==OpenAIErrorCategory.InvalidRequest,"22");T(OpenAIProviderAdapter.Classify(400,"unsupported_parameter max_tokens")==OpenAIErrorCategory.UnsupportedParameter,"23");T(OpenAIProviderAdapter.Classify(404,"model_not_found")==OpenAIErrorCategory.ModelNotFound,"24");T(OpenAIProviderAdapter.Classify(503,"")==OpenAIErrorCategory.Server,"25");T(OpenAIProviderAdapter.Classify(418,"")==OpenAIErrorCategory.Unknown,"26");
 T(OpenAIProviderAdapter.ParseOutputText("{\"type\":\"output_text\",\"text\":\"OK\"}")=="OK","27");T(OpenAIProviderAdapter.ParseOutputText("{\"text\":\"Гаразд\",\"type\":\"output_text\"}")=="Гаразд","28");T(OpenAIProviderAdapter.ParseOutputText("{}")=="","29");T(q.StartsWith("{"),"30");T(q.EndsWith("}"),"31");T(q.Contains("\"input\":["),"32");T(q.Contains("\"role\":\"user\""),"33");T(!q.Contains("chat/completions"),"34");T(!q.Contains("stream_options"),"35");T(!q.Contains("completion_tokens"),"36");T(OpenAIProviderAdapter.ModelsEndpoint.EndsWith("/v1/models"),"37");
 Environment.SetEnvironmentVariable("OPENAI_RIMTALK",null);Environment.SetEnvironmentVariable("OPENAI_RIMCHAT",null);Environment.SetEnvironmentVariable("OPENAI_RIMTRANS",null);Environment.SetEnvironmentVariable("OPENAI_API_KEY",null);
 Environment.SetEnvironmentVariable(OpenAIProviderAdapter.CredentialVariable,secret);T(OpenAIProviderAdapter.CredentialVariable=="OPENAI_RIMAI","38a");T(OpenAIProviderAdapter.CredentialPresent,"38");T(!OpenAIProviderAdapter.CredentialDisplay.Contains(secret),"39");T(OpenAIProviderAdapter.CredentialDisplay.Contains("OPENAI_RIMAI"),"39b");Environment.SetEnvironmentVariable(OpenAIProviderAdapter.CredentialVariable,null);T(!OpenAIProviderAdapter.CredentialPresent,"40");Environment.SetEnvironmentVariable("OPENAI_API_KEY",secret);T(!OpenAIProviderAdapter.CredentialPresent,"41");Environment.SetEnvironmentVariable("OPENAI_RIMCHAT",secret);T(!OpenAIProviderAdapter.CredentialPresent,"42");T(!OpenAIProviderAdapter.CredentialDisplay.Contains("OPENAI_RIMCHAT"),"42b");Environment.SetEnvironmentVariable("OPENAI_RIMCHAT",null);Environment.SetEnvironmentVariable("OPENAI_RIMTRANS",secret);T(!OpenAIProviderAdapter.CredentialPresent,"43");T(!q.Contains(secret),"44");T(OpenAIProviderAdapter.CredentialDisplay.Contains("OPENAI_RIMAI"),"45");T(OpenAIProviderAdapter.BuildRequest("x",new List<(Ustas.RimAI.Communication.Data.Role,string)>{(Ustas.RimAI.Communication.Data.Role.AI,"a")},1).Contains("assistant"),"46");T(OpenAIProviderAdapter.ParseOutputText("{\"type\":\"output_text\",\"text\":\"one\"} {\"text\":\"two\",\"type\":\"output_text\"}")=="one two","47");n+=CommunicationPersistenceTests.Run();Console.WriteLine("OPENAI_FOCUSED_TESTS_OK passed="+n);Console.WriteLine("TESTS total="+n+" failed=0");return 0;
 }finally{Environment.SetEnvironmentVariable(OpenAIProviderAdapter.CredentialVariable,old);Environment.SetEnvironmentVariable("OPENAI_RIMTALK",talk);Environment.SetEnvironmentVariable("OPENAI_RIMCHAT",chat);Environment.SetEnvironmentVariable("OPENAI_RIMTRANS",trans);Environment.SetEnvironmentVariable("OPENAI_API_KEY",api);}}
}
