using System.Collections.Generic;
using Ustas.RimAI.Communication.Data;
using Ustas.RimAI.Communication.Data;
using Verse;

namespace Ustas.RimAI.Communication.Prompt;

/// <summary>
/// Prompt rendering context - contains all information needed for parsing.
/// Used by ScribanParser to provide data for templates.
/// </summary>
public class PromptContext
{
    /// <summary>Current primary pawn</summary>
    public Pawn CurrentPawn { get; set; }
    
    /// <summary>All pawns participating in the dialogue</summary>
    public List<Pawn> AllPawns { get; set; }
    
    /// <summary>Current map</summary>
    public Map Map { get; set; }
    
    /// <summary>Variable store</summary>
    public VariableStore VariableStore { get; set; }
    
    /// <summary>Talk request</summary>
    public TalkRequest TalkRequest { get; set; }
    
    /// <summary>Pawn context generated by ContextBuilder</summary>
    public string PawnContext { get; set; }
    
    /// <summary>Dialogue type description (monologue/conversation/urgent, etc.)</summary>
    public string DialogueType { get; set; }
    
    /// <summary>Intent description</summary>
    public string Intent { get; set; }
    
    /// <summary>Topic description</summary>
    public string ConversationTopic { get; set; }
    
    /// <summary>Dialogue status description (initiator's current state)</summary>
    public string DialogueStatus { get; set; }
    
    /// <summary>Full dialogue prompt (result of DecoratePrompt, includes time/weather/location/etc.)</summary>
    public string DialoguePrompt { get; set; }
    
    /// <summary>Chat history (Role, Message) - for inserting history in entries</summary>
    public List<(Role role, string message)> ChatHistory { get; set; } = new();

    public List<(Role role, string message)> GetChatHistory(bool simplified)
    {
        if (CurrentPawn == null) return [];
        return TalkHistory.GetMessageHistory(CurrentPawn, simplified);
    }

    // Convenience properties - obtained from TalkRequest
    public bool IsMonologue => TalkRequest?.IsMonologue ?? false;
    public TalkType TalkType => TalkRequest?.TalkType ?? TalkType.Other;
    public string UserPrompt => TalkType == TalkType.User ? TalkRequest?.RawPrompt : null;

    // Compatibility property - Pawns alias
    public List<Pawn> Pawns => AllPawns;
    
    /// <summary>Current pawn index in section iteration (for {{index}} variable)</summary>
    public int ScopedPawnIndex { get; set; }

    /// <summary>Whether this context is being used for preview (e.g. settings menu)</summary>
    public bool IsPreview { get; set; }

    /// <summary>True when the primary typed Memory context provider supplied this turn.</summary>
    public bool UsedTypedMemoryContext { get; set; }

    public string TypedMemorySource { get; set; }

    public PromptContext()
    {
        AllPawns = [];
    }

    public PromptContext(Pawn pawn, VariableStore variableStore = null)
    {
        CurrentPawn = pawn;
        AllPawns = pawn != null ? [pawn] : [];
        Map = pawn?.Map;
        VariableStore = variableStore ?? PromptManager.Instance?.VariableStore ?? new VariableStore();
    }

    public PromptContext(List<Pawn> pawns, VariableStore variableStore = null)
    {
        AllPawns = pawns ?? [];
        CurrentPawn = AllPawns.Count > 0 ? AllPawns[0] : null;
        Map = CurrentPawn?.Map;
        VariableStore = variableStore ?? PromptManager.Instance?.VariableStore ?? new VariableStore();
    }

    /// <summary>
    /// Creates context from TalkRequest.
    /// Uses Participants from TalkRequest if available, otherwise falls back to provided pawns list.
    /// </summary>
    public static PromptContext FromTalkRequest(TalkRequest request, List<Pawn> pawns = null)
    {
        // Prefer TalkRequest.Participants (filled in sync layer)
        if (request != null && (request.Participants == null || request.Participants.Count == 0) && pawns != null)
            request.Participants = pawns;

        var participants = request?.Participants ?? pawns ?? new List<Pawn>();
        
        return new PromptContext
        {
            TalkRequest = request,
            AllPawns = participants,
            CurrentPawn = request?.Initiator,
            Map = request?.Initiator?.Map,
            VariableStore = PromptManager.Instance?.VariableStore ?? new VariableStore(),
            // Use data already built in TalkRequest
            PawnContext = request?.Context,
            // DialogueType and DialogueStatus are set separately by the caller
            // to avoid pollution from DecoratePrompt which fills request.Prompt with full context
            ChatHistory = request?.Initiator != null
                ? TalkHistory.GetMessageHistory(request.Initiator)
                : []
        };
    }
}
